/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as PetsMineRouteImport } from './routes/pets/mine'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { Route as PetsPetIdEditRouteImport } from './routes/pets_.$petId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsMineRoute = PetsMineRouteImport.update({
  id: '/pets/mine',
  path: '/pets/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdEditRoute = PetsPetIdEditRouteImport.update({
  id: '/pets_/$petId/edit',
  path: '/pets/$petId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/mine': typeof PetsMineRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/mine': typeof PetsMineRoute
  '/pets/new': typeof PetsNewRoute
  '/pets': typeof PetsIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/mine': typeof PetsMineRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
  '/pets_/$petId/edit': typeof PetsPetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/pets/$petId'
    | '/pets/mine'
    | '/pets/new'
    | '/pets/'
    | '/pets/$petId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/pets/$petId'
    | '/pets/mine'
    | '/pets/new'
    | '/pets'
    | '/pets/$petId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/pets/$petId'
    | '/pets/mine'
    | '/pets/new'
    | '/pets/'
    | '/pets_/$petId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsMineRoute: typeof PetsMineRoute
  PetsNewRoute: typeof PetsNewRoute
  PetsIndexRoute: typeof PetsIndexRoute
  PetsPetIdEditRoute: typeof PetsPetIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/mine': {
      id: '/pets/mine'
      path: '/pets/mine'
      fullPath: '/pets/mine'
      preLoaderRoute: typeof PetsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets_/$petId/edit': {
      id: '/pets_/$petId/edit'
      path: '/pets/$petId/edit'
      fullPath: '/pets/$petId/edit'
      preLoaderRoute: typeof PetsPetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  PetsMineRoute: PetsMineRoute,
  PetsNewRoute: PetsNewRoute,
  PetsIndexRoute: PetsIndexRoute,
  PetsPetIdEditRoute: PetsPetIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
